version: '3.8'
services:
  server:
    #build: ./soccer-quiz-server
    image: minseo08/soccer-quiz-backend:latest
    ports:
      - "4000:4000"
    volumes:
      - ./soccer-quiz-server/.env:/usr/src/app/.env
    restart: always
  
  app:
    #build: ./soccer-quiz
    image: minseo08/soccer-quiz-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: always