name: Football Quiz CI/CD

on:
  push:
    branches: [ main ] # main 브랜치에 코드가 올라오면 실행

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 1. 서버(Back-end) 빌드 및 푸시
      - name: Build and push Server
        uses: docker/build-push-action@v5
        with:
          context: ./soccer-quiz-server # 서버 폴더명 확인!
          push: true
          tags: minseo08/soccer-quiz-backend:latest

      # 2. 앱(Front-end) 빌드 및 푸시
      - name: Build and push App
        uses: docker/build-push-action@v5
        with:
          context: ./soccer-quiz # 리액트 앱 폴더명 확인!
          push: true
          tags: minseo08/soccer-quiz-frontend:latest

  deploy:
    needs: build-and-push # 빌드가 성공해야 배포 시작
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/soccer-quiz-project 

            sudo docker-compose pull

            sudo docker-compose up -d
            
            sudo docker image prune -f